apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-node-app
    version: 1
  name: sample-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-node-app
    spec:
      containers:
      - image: 228722872020/sample-node-app:1.0
        name: sample-node-app
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_SERVER_URL
            value: "mongodb-service"
          - name: MONGO_PORT
            value: "27017"
