apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-node-app
  name: sample-node-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app: sample-node-app
  type: NodePort
