apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes
    repoURL: 'https://github.com/bombadeb/argocd-poc.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated: null

